var mongoose = require("mongoose");
var config = require("../config/config.js");
db = mongoose.createConnection(config.DBHOST , config.DBNAME);
var Schema = mongoose.Schema;

var Score = new Schema({
  "6" : String,
  "9" : String,
  "10" : String,
  "11" :String,
  "12" : String,
  "13" : String,
  "14" : String,
  "16" : String,
  "19" : String,
  "20" : String,
  "21" : String,
  "22" : String,
  "26" : String,
  "school" : String,
  "class_num" : String,
  "name" : String,
  "student_id" : String,
  "twon_or_country" : String,
  "total" : String,
  "1_1" : String,
  "1_2" : String,
  "1_3" : String,
  "2_1" : String,
  "2_2" : String,
  "3_1" : String,
  "3_2" : String,
  "4_1" : String,
  "4_2" :String,
  "5_1" : String,
  "5_2" : String,
  "7_1" : String,
  "7_2" : String,
  "8_1" : String,
  "8_2" : String,
  "15_1" : String,
  "15_2" : String,
  "15_3" : String,
  "15_4" : String,
  "15_5" : String,
  "17_1" : String,
  "17_2" : String,
  "18_1" : String,
  "18_2" : String,
  "23_1" : String,
  "23_2" : String,
  "23_3" : String,
  "24_1" : String,
  "24_2" :String,
  "25_1" : String,
  "25_2" : String,
  "sex" : String,
  "paper_id" : String

});
module.exports = db.model("score" ,Score ,"score");